steps:
# Build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/script-ja-website:$COMMIT_SHA', '.'] # Changed YOUR_SERVICE_NAME

# Push the container image to Google Container Registry (GCR)
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/script-ja-website:$COMMIT_SHA'] # Changed YOUR_SERVICE_NAME

# Deploy container image to Cloud Run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args:
    - 'run'
    - 'deploy'
    - 'script-ja-website' # This is your Cloud Run service name
    - '--image'
    - 'gcr.io/$PROJECT_ID/script-ja-website:$COMMIT_SHA' # Changed YOUR_SERVICE_NAME to match the image built
    - '--region'
    - 'us-central1' # Or your specific region, e.g., us-east1, europe-west1
    - '--platform'
    - 'managed'
    - '--allow-unauthenticated'
    # Add other flags as needed, e.g., --port, --env-vars, --memory, etc.

images:
- 'gcr.io/$PROJECT_ID/script-ja-website:$COMMIT_SHA' # Changed YOUR_SERVICE_NAME